In [1]:
import numpy as np

In [52]:
a = np.array([1,2,3,4])
print(a)
print(type(a))
print(a.shape)


[1 2 3 4]
<class 'numpy.ndarray'>
(4,)


In [10]:
student = np.dtype([('name','S20'),('age','i1'),('marks','f4')])
print(student)

a = np.array([('abc',18,55),('xyz',19,75)],dtype=student)

print(a)

[('name', 'S20'), ('age', 'i1'), ('marks', '<f4')]
[(b'abc', 18,  55.) (b'xyz', 19,  75.)]


In [12]:
b = np.array([[1,2,3],[4,5,6]])

print(b.shape)

(2, 3)


In [14]:
b = np.array([[1,2,3],[4,5,6]])
b.shape=(3,2)
print(b.shape)
print(b)

(3, 2)
[[1 2]
 [3 4]
 [5 6]]


In [19]:
c = np.arange(24)
print(c)

d = c.reshape(2,4,3)
print(d) 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [21]:
e = np.array([1,2,3,4,5],dtype=np.int8)
e.itemsize

e.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [22]:
x=np.empty([3,2],dtype = int)
print(x)

[[0 0]
 [0 0]
 [0 0]]


In [23]:
y=np.zeros(5)
print(y)

[ 0.  0.  0.  0.  0.]


In [24]:
z=np.zeros((5,),dtype=np.int)
print(z)

[0 0 0 0 0]


In [26]:
l = [1,2,3]
m = np.asarray(l,dtype=float)

print(m)

[ 1.  2.  3.]


In [29]:
list = range(5)
print(list)

it =iter(list)

x=np.fromiter(it,dtype=float)
print(x)

range(0, 5)
[ 0.  1.  2.  3.  4.]


In [30]:
m=np.linspace(10,20,5)
print(m)

[ 10.   12.5  15.   17.5  20. ]


In [36]:
xs = [3,1,2]
print(xs,xs[2])
print(xs[-1])
xs[2]='foo'
print(xs)
xs.append('bar')
print(xs)
x=xs.pop()
print(x)

[3, 1, 2] 2
2
[3, 1, 'foo']
[3, 1, 'foo', 'bar']
bar


In [45]:
animals = ['cat','dog','monkey']
for animal in animals:
    print(animal)

cat
dog
monkey


In [47]:
nums = [0,1,2,3,4]

squares = []
for x in nums:
    squares.append(x**2)
print(squares)

[0, 1, 4, 9, 16]


In [53]:
d = np.eye(3)
print(d)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [54]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
row_r1=a[1,:]
print(row_r1, row_r1.shape)

[5 6 7 8] (4,)


In [55]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
print(x.shape)

(2, 2)
